# Command to install some useful packages

Remove comment to install packages and update pip

create virtual environment and activate it 
1.    ` python -m venv env_name ` \# create virtual environment
2.   ` env_name/bin/activate.bat ` \# activate virtual environment
 


In [2]:
# !pip install pandas
# !pip install numpy
# !pip install sklearn
# !pip install matplotlib
# !pip install scikit-learn
# !pip install scipy
# !python -m pip install --upgrade pip


# Numpy tutorial

In [3]:
import numpy as np

## Numpy array Creation Methods

In [4]:
## 1-D array
np_1d_array = np.array([1,2,3,4,5])
print(np_1d_array)
np_1d_array.shape

[1 2 3 4 5]


(5,)

In [5]:
#2-D array
np_2d_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np_2d_array)
np_2d_array.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [6]:
#zeros array
np_zeros_array = np.zeros((3,4)) # 3 rows and 4 columns with all zeros
print(np_zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
#ones array
np_ones_array = np.ones((3,4)) # 3 rows and 4 columns with all ones
print(np_ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
# array with specific values
np_10_array = np.full((3,4),10) # 3 rows and 4 columns with all 10
print(np_10_array)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [9]:
#indentity matrix
np_identity_matrix = np.eye(3) # 3*3 Square matrix with 1 on the diagonal and 0 elsewhere
print(np_identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#random  values array
np_random_array = np.random.random((3,4)) # 3 rows and 4 columns with random values
print(np_random_array)



[[0.69478413 0.09119802 0.81720478 0.6967667 ]
 [0.59526643 0.9473318  0.29980941 0.90429499]
 [0.59231932 0.1774471  0.7893203  0.15056442]]


In [11]:
#Random int  values array within range
np_random_int_array = np.random.randint(1,10,(3,4)) # 3 rows and 4 columns with random values within range 1-9
print(np_random_int_array)

[[9 6 4 7]
 [1 6 5 6]
 [9 2 3 8]]


In [12]:
# evenly spaced values  with no of values 
np_evenly_spaced_array = np.linspace(1,25,5) # 5 evenly spaced values between 1 and 25
print(np_evenly_spaced_array)

[ 1.  7. 13. 19. 25.]


In [13]:
# evenly spaced values with step size
np_arange_array = np.arange(1,25,5) # evenly spaced values between 1 and 25 with step size 5
print(np_arange_array)


[ 1  6 11 16 21]


In [14]:
# create numpy array fromn list
python_list = [1,2,3,4,5]
np_list_array = np.array(python_list) # create numpy array from python list
print(np_list_array)
np_list_array.shape
type(np_list_array)


[1 2 3 4 5]


numpy.ndarray

## Analyzing the numpy array

In [15]:
# create random int  array 
np_random_int_array = np.random.randint(1,10,(3,4)) # 3 rows and 4 columns with random values within range 1-9
print(np_random_int_array)


[[3 4 3 5]
 [1 2 7 6]
 [8 9 6 4]]


In [16]:
# Array Dimensions
print(np_random_int_array.shape)

# no of  dimensions
print (np_random_int_array.ndim)

# total no of elements in an array
print(np_random_int_array.size)

# Array Data Type
print(np_random_int_array.dtype)


(3, 4)
2
12
int32


## Mathematical operations on numpy arrays


In [17]:
# create numpy array 
np_random1 = np.random.randint(1,10,(3,4))
print('First Array: \n',np_random1)
np_random2 = np.random.randint(10,20,(3,4))
print('Second Array: \n',np_random2)


First Array: 
 [[1 4 1 7]
 [8 4 6 3]
 [9 4 8 8]]
Second Array: 
 [[19 18 17 17]
 [14 15 11 17]
 [14 18 17 13]]


In [18]:

# add two arrays
np_add_array = np_random1 + np_random2
print('Suma Array: \n',np_add_array)

Suma Array: 
 [[20 22 18 24]
 [22 19 17 20]
 [23 22 25 21]]


In [19]:
# subtract two arrays
print (np_random1-np_random2)

# multiply two arrays
print (np_random1*np_random2)

# divide two arrays
print (np_random1/np_random2)


[[-18 -14 -16 -10]
 [ -6 -11  -5 -14]
 [ -5 -14  -9  -5]]
[[ 19  72  17 119]
 [112  60  66  51]
 [126  72 136 104]]
[[0.05263158 0.22222222 0.05882353 0.41176471]
 [0.57142857 0.26666667 0.54545455 0.17647059]
 [0.64285714 0.22222222 0.47058824 0.61538462]]


In [20]:
#using methods
print(np.add(np_random1,np_random2))
print(np.subtract(np_random1,np_random2))
print(np.multiply(np_random1,np_random2))
print(np.divide(np_random1,np_random2))


[[20 22 18 24]
 [22 19 17 20]
 [23 22 25 21]]
[[-18 -14 -16 -10]
 [ -6 -11  -5 -14]
 [ -5 -14  -9  -5]]
[[ 19  72  17 119]
 [112  60  66  51]
 [126  72 136 104]]
[[0.05263158 0.22222222 0.05882353 0.41176471]
 [0.57142857 0.26666667 0.54545455 0.17647059]
 [0.64285714 0.22222222 0.47058824 0.61538462]]


In [21]:
# universal functions
print(np.sqrt(np_random1)) # square root
print(np_random1**3) # power of 3
print(np.exp(np_random1)) # exponential
print(np.log(np_random1)) # logarithm
print(np.log10(np_random1)) # logarithm base 10
print(np.sin(np_random1)) # sine
print(np.cos(np_random1)) # cosine 
print(np.tan(np_random1)) # tangent
print(np.ceil(np_random1)) # ceiling
print(np.floor(np_random1)) # floor
print(np.rint(np_random1)) # round
print(np.fabs(np_random1)) # returns the absolute value of the input array
print(np_random1)


[[1.         2.         1.         2.64575131]
 [2.82842712 2.         2.44948974 1.73205081]
 [3.         2.         2.82842712 2.82842712]]
[[  1  64   1 343]
 [512  64 216  27]
 [729  64 512 512]]
[[2.71828183e+00 5.45981500e+01 2.71828183e+00 1.09663316e+03]
 [2.98095799e+03 5.45981500e+01 4.03428793e+02 2.00855369e+01]
 [8.10308393e+03 5.45981500e+01 2.98095799e+03 2.98095799e+03]]
[[0.         1.38629436 0.         1.94591015]
 [2.07944154 1.38629436 1.79175947 1.09861229]
 [2.19722458 1.38629436 2.07944154 2.07944154]]
[[0.         0.60205999 0.         0.84509804]
 [0.90308999 0.60205999 0.77815125 0.47712125]
 [0.95424251 0.60205999 0.90308999 0.90308999]]
[[ 0.84147098 -0.7568025   0.84147098  0.6569866 ]
 [ 0.98935825 -0.7568025  -0.2794155   0.14112001]
 [ 0.41211849 -0.7568025   0.98935825  0.98935825]]
[[ 0.54030231 -0.65364362  0.54030231  0.75390225]
 [-0.14550003 -0.65364362  0.96017029 -0.9899925 ]
 [-0.91113026 -0.65364362 -0.14550003 -0.14550003]]
[[ 1.55740772  1.1

In [31]:
# Matrix multiplication

Matrix_1= np.ones((4,6))
Matrix_2= np.ones((6,2))

Mat_mul= np.dot(Matrix_1,Matrix_2)
print(Mat_mul)


[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


## Array Manipulation

In [22]:
# create numpy array
np_random1 = np.random.randint(1,10,(3,4))
print(np_random1)
print(np_random1.shape)

[[8 3 9 4]
 [8 1 5 2]
 [1 7 5 8]]
(3, 4)


In [28]:
# transpose array
trans_array_1 = np_random1.T  

# another mentod to transpose 
trans_array_2 = np.transpose (np_random1)

print(trans_array_1)
print(trans_array_1.shape)

result= (trans_array_1 == trans_array_2)

print( "Is np.transpose() and .T  gives same value?? ", result )

[[8 8 1]
 [3 1 7]
 [9 5 5]
 [4 2 8]]
(4, 3)
Is np.transpose() and .T  gives same value??  [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Reshaping Array
np_reshape_array = np_random1.reshape (4,3)
print (np_reshape_array)
print( np_reshape_array.shape)


[[6 6 7]
 [5 2 6]
 [4 6 6]
 [6 8 6]]
(4, 3)


In [ ]:
# Indexing 
np_random1 = np.random.randint(1,10,(3,4))
print(np_random1)

print(np_random1[2,3])

[[6 4 7 2]
 [7 6 6 3]
 [2 1 3 6]]
6


In [ ]:
#slicing
print(np_random1[1:3,0]) # 2nd row to 3rd row and 1st column

#iteration
for row in np_random1:
    print(row)

[7 2]
[6 4 7 2]
[7 6 6 3]
[2 1 3 6]


In [25]:
# Normalizaton
np_array=np.random.randint(1,10,(3,4))
Zmax, Zmin = np_array.max(), np_array.min()
np_array = (np_array - Zmin)/(Zmax - Zmin)
print(np_array)

[[0.85714286 1.         0.28571429 0.42857143]
 [0.         0.85714286 0.71428571 0.14285714]
 [1.         0.14285714 0.42857143 1.        ]]


# Pandas Tutorial

## Import library and Datas

In [14]:
import pandas as pd

#importing data from sklearn library
from sklearn.datasets import fetch_california_housing
california_housing_dataset=fetch_california_housing()






## DataFrame Creation

In [22]:
# convert dataset to dataframe and assign column names
california_housing_dataframe =pd.DataFrame(california_housing_dataset.data , columns=california_housing_dataset.feature_names)  


#importing data from csv file
diabetes_dataframe = pd.read_csv("diabetes.csv")

# #save to csv ( california Housing Dataset)
# california_housing_dataframe.to_csv('california_housing.csv')

## DataFrame Informaion


In [23]:
# print first five rows with headers 
california_housing_dataframe.head()
# diabetes_dataframe.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [25]:
#Dimension  of dataframe
california_housing_dataframe.shape
# diabetes_dataframe.shape


(20640, 8)

In [24]:
#describe dataframe (summary)
california_housing_dataframe.describe()
# diabetes_dataframe.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000