# Command to install some useful packages

Remove comment to install packages and update pip

create virtual environment and activate it 
1.    ` python -m venv env_name ` \# create virtual environment
2.   ` env_name/Scripts/activate.bat ` \# activate virtual environment
 


In [32]:
# !pip install pandas
# !pip install numpy
# !pip install sklearn
# !pip install matplotlib
# !pip install scikit-learn
# !pip install scipy
# !python -m pip install --upgrade pip


# Numpy tutorial

In [33]:
import numpy as np

## Numpy array Creation Methods

In [34]:
## 1-D array
np_1d_array = np.array([1,2,3,4,5])
print(np_1d_array)
np_1d_array.shape

[1 2 3 4 5]


(5,)

In [35]:
#2-D array
np_2d_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np_2d_array)
np_2d_array.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [36]:
#zeros array
np_zeros_array = np.zeros((3,4)) # 3 rows and 4 columns with all zeros
print(np_zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
#ones array
np_ones_array = np.ones((3,4)) # 3 rows and 4 columns with all ones
print(np_ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [38]:
# array with specific values
np_10_array = np.full((3,4),10) # 3 rows and 4 columns with all 10
print(np_10_array)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [39]:
#indentity matrix
np_identity_matrix = np.eye(3) # 3*3 Square matrix with 1 on the diagonal and 0 elsewhere
print(np_identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
#random  values array
np_random_array = np.random.random((3,4)) # 3 rows and 4 columns with random values
print(np_random_array)



[[0.25132657 0.28208803 0.41789439 0.77862046]
 [0.29541514 0.87473568 0.84656884 0.64319784]
 [0.38415796 0.15920155 0.99099811 0.18293071]]


In [41]:
#Random int  values array within range
np_random_int_array = np.random.randint(1,10,(3,4)) # 3 rows and 4 columns with random values within range 1-9
print(np_random_int_array)

[[9 7 3 3]
 [2 3 8 3]
 [7 3 5 4]]


In [42]:
# evenly spaced values  with no of values 
np_evenly_spaced_array = np.linspace(1,25,5) # 5 evenly spaced values between 1 and 25
print(np_evenly_spaced_array)

[ 1.  7. 13. 19. 25.]


In [43]:
# evenly spaced values with step size
np_arange_array = np.arange(1,25,5) # evenly spaced values between 1 and 25 with step size 5
print(np_arange_array)


[ 1  6 11 16 21]


In [44]:
# create numpy array fromn list
python_list = [1,2,3,4,5]
np_list_array = np.array(python_list) # create numpy array from python list
print(np_list_array)
np_list_array.shape
type(np_list_array)


[1 2 3 4 5]


numpy.ndarray

## Analyzing the numpy array

In [45]:
# create random int  array 
np_random_int_array = np.random.randint(1,10,(3,4)) # 3 rows and 4 columns with random values within range 1-9
print(np_random_int_array)


[[2 2 7 1]
 [4 5 3 5]
 [5 5 6 1]]


In [46]:
# Array Dimensions
print(np_random_int_array.shape)

# no of  dimensions
print (np_random_int_array.ndim)

# total no of elements in an array
print(np_random_int_array.size)

# Array Data Type
print(np_random_int_array.dtype)


(3, 4)
2
12
int32


## Mathematical operations on numpy arrays


In [47]:
# create numpy array 
np_random1 = np.random.randint(1,10,(3,4))
print('First Array: \n',np_random1)
np_random2 = np.random.randint(10,20,(3,4))
print('Second Array: \n',np_random2)


First Array: 
 [[5 4 5 6]
 [5 4 4 4]
 [5 5 3 3]]
Second Array: 
 [[18 19 11 10]
 [17 19 10 10]
 [16 12 17 11]]


In [48]:

# add two arrays
np_add_array = np_random1 + np_random2
print('Suma Array: \n',np_add_array)

Suma Array: 
 [[23 23 16 16]
 [22 23 14 14]
 [21 17 20 14]]


In [49]:
# subtract two arrays
print (np_random1-np_random2)

# multiply two arrays
print (np_random1*np_random2)

# divide two arrays
print (np_random1/np_random2)


[[-13 -15  -6  -4]
 [-12 -15  -6  -6]
 [-11  -7 -14  -8]]
[[90 76 55 60]
 [85 76 40 40]
 [80 60 51 33]]
[[0.27777778 0.21052632 0.45454545 0.6       ]
 [0.29411765 0.21052632 0.4        0.4       ]
 [0.3125     0.41666667 0.17647059 0.27272727]]


In [50]:
#using methods
print(np.add(np_random1,np_random2))
print(np.subtract(np_random1,np_random2))
print(np.multiply(np_random1,np_random2))
print(np.divide(np_random1,np_random2))


[[23 23 16 16]
 [22 23 14 14]
 [21 17 20 14]]
[[-13 -15  -6  -4]
 [-12 -15  -6  -6]
 [-11  -7 -14  -8]]
[[90 76 55 60]
 [85 76 40 40]
 [80 60 51 33]]
[[0.27777778 0.21052632 0.45454545 0.6       ]
 [0.29411765 0.21052632 0.4        0.4       ]
 [0.3125     0.41666667 0.17647059 0.27272727]]


In [51]:
# universal functions
print(np.sqrt(np_random1)) # square root
print(np_random1**3) # power of 3
print(np.exp(np_random1)) # exponential
print(np.log(np_random1)) # logarithm
print(np.log10(np_random1)) # logarithm base 10
print(np.sin(np_random1)) # sine
print(np.cos(np_random1)) # cosine 
print(np.tan(np_random1)) # tangent
print(np.ceil(np_random1)) # ceiling
print(np.floor(np_random1)) # floor
print(np.rint(np_random1)) # round
print(np.fabs(np_random1)) # returns the absolute value of the input array
print(np_random1)


[[2.23606798 2.         2.23606798 2.44948974]
 [2.23606798 2.         2.         2.        ]
 [2.23606798 2.23606798 1.73205081 1.73205081]]
[[125  64 125 216]
 [125  64  64  64]
 [125 125  27  27]]
[[148.4131591   54.59815003 148.4131591  403.42879349]
 [148.4131591   54.59815003  54.59815003  54.59815003]
 [148.4131591  148.4131591   20.08553692  20.08553692]]
[[1.60943791 1.38629436 1.60943791 1.79175947]
 [1.60943791 1.38629436 1.38629436 1.38629436]
 [1.60943791 1.60943791 1.09861229 1.09861229]]
[[0.69897    0.60205999 0.69897    0.77815125]
 [0.69897    0.60205999 0.60205999 0.60205999]
 [0.69897    0.69897    0.47712125 0.47712125]]
[[-0.95892427 -0.7568025  -0.95892427 -0.2794155 ]
 [-0.95892427 -0.7568025  -0.7568025  -0.7568025 ]
 [-0.95892427 -0.95892427  0.14112001  0.14112001]]
[[ 0.28366219 -0.65364362  0.28366219  0.96017029]
 [ 0.28366219 -0.65364362 -0.65364362 -0.65364362]
 [ 0.28366219  0.28366219 -0.9899925  -0.9899925 ]]
[[-3.38051501  1.15782128 -3.38051501 -0.2

In [52]:
# Matrix multiplication

Matrix_1= np.ones((4,6))
Matrix_2= np.ones((6,2))

Mat_mul= np.dot(Matrix_1,Matrix_2)
print(Mat_mul)


[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


## Array Manipulation

In [53]:
# create numpy array
np_random1 = np.random.randint(1,10,(3,4))
print(np_random1)
print(np_random1.shape)

[[1 9 8 8]
 [1 4 4 4]
 [8 1 3 1]]
(3, 4)


In [54]:
# transpose array
trans_array_1 = np_random1.T  

# another mentod to transpose 
trans_array_2 = np.transpose (np_random1)

print(trans_array_1)
print(trans_array_1.shape)

result= (trans_array_1 == trans_array_2)

print( "Is np.transpose() and .T  gives same value?? ", result )

[[1 1 8]
 [9 4 1]
 [8 4 3]
 [8 4 1]]
(4, 3)
Is np.transpose() and .T  gives same value??  [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [55]:
# Reshaping Array
np_reshape_array = np_random1.reshape (4,3)
print (np_reshape_array)
print( np_reshape_array.shape)


[[1 9 8]
 [8 1 4]
 [4 4 8]
 [1 3 1]]
(4, 3)


In [56]:
# Indexing 
np_random1 = np.random.randint(1,10,(3,4))
print(np_random1)

print(np_random1[2,3])

[[3 9 4 3]
 [7 3 2 9]
 [7 4 1 9]]
9


In [57]:
#slicing
print(np_random1[1:3,0]) # 2nd row to 3rd row and 1st column

#iteration
for row in np_random1:
    print(row)

[7 7]
[3 9 4 3]
[7 3 2 9]
[7 4 1 9]


In [58]:
# Normalizaton
np_array=np.random.randint(1,10,(3,4))
Zmax, Zmin = np_array.max(), np_array.min()
np_array = (np_array - Zmin)/(Zmax - Zmin)
print(np_array)

[[0.625 0.    0.625 0.125]
 [0.875 0.125 0.    0.625]
 [0.875 0.375 0.125 1.   ]]


# Pandas Tutorial

## Import library and Datas

In [59]:
import pandas as pd

# #importing data from sklearn library
from sklearn.datasets import fetch_california_housing
california_housing_dataset=fetch_california_housing()

## DataFrame Creation

In [60]:
# convert dataset to dataframe and assign column names
california_housing_dataframe=pd.DataFrame(california_housing_dataset.data,columns=california_housing_dataset.feature_names)

#  directly read from CSV file
# california_housing_dataframe =pd.read_csv('california_housing.csv' )  


#importing data from csv file
diabetes_dataframe = pd.read_csv("diabetes.csv")

# from random data
df_random = pd.DataFrame(np.random.rand(20,10)) # 20 rows 10 columns  , all values are random in between 0-1

#from json data
# df_json = pd.read_json("file_name.json") 

## DataFrame Inspection


In [61]:
# print first five rows with headers 
california_housing_dataframe.head()
# diabetes_dataframe.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [62]:
# print last five rows with headers voila

california_housing_dataframe.tail()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24

In [63]:
#Dimension  of dataframe
california_housing_dataframe.shape
# diabetes_dataframe.shape


(20640, 8)

In [79]:
#describe dataframe (summary)
california_housing_dataframe.describe()
# diabetes_dataframe.describe()

# OR can use indivuidual functions
# california_housing_dataframe.count()
# california_housing_dataframe.min()
# california_housing_dataframe.max()
# california_housing_dataframe.mean()
# california_housing_dataframe.std()
# california_housing_dataframe.var()


MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude  
count  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704  
std       10.386050      2.135952      2.003532  
min        0.692308     32.540000   -124.350000  
25%        2.429741     33.930000   -121.800000  
50%        2.818116     34.260000   -118.490000  
75%        3.282261     37.710000   -118.010000  
max     1243.333333     41.950000   -114.310000

In [65]:
# informaton about dataframe
california_housing_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


 find no of missing values in dataframe
 

In [66]:

california_housing_dataframe.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

 Counting the values based on column(Label)


In [67]:

#california_housing_dataframe['HouseAge'].value_counts()
                    ####OR
#california_housing_dataframe.value_counts('HouseAge')

diabetes_dataframe.value_counts('Outcome')


Outcome
0    500
1    268
dtype: int64

Correlation between two columns

In [68]:
# positive correlation if one increase the other also increase
# negative correlation if one increase the other decrease

california_housing_dataframe.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   

            Latitude  Longitude  
MedInc     -0.079809  -0.015176  
HouseAge    0.011173  -0.108197  
AveRooms    0.106389  -0.027540  
AveBedrms   0.069721   0.013344  
Population -0.108785   0.099773  
AveOccup    0.002366   0.002476  
Latitude    1.000000  -0.924664  
Longitude  -0.924664   1.000000

Locate Rows and columns 


In [110]:
#use iloc to locate specific rows and columns

# #Row (3rd)
# california_housing_dataframe.iloc[2]

# # Row (last)
# california_housing_dataframe.iloc[-1]

# #column (2nd)
# california_housing_dataframe.iloc[:,1]

# california_housing_dataframe.iloc[0:5,0:6] # first 5 rows and first 6 columns

 


0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ... 
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20640, dtype: float64

## DataFrame Manipulation

Save to file

In [69]:
# save to csv ( california Housing Dataset)
# california_housing_dataframe.to_csv('california_housing.csv')

# save to excel ( california Housing Dataset) ( need to install openpyxl library)
# california_housing_dataframe.to_excel('california_housing.xlsx')

In [70]:
# view in numpy array format'
california_housing_dataframe.to_numpy()

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

Add column

In [83]:
# add target  to dataframe
california_housing_dataframe['target'] = california_housing_dataset.target

california_housing_dataframe.head()


MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

Remove columns and Rows 

In [ ]:
# # remove first(index=0) row(axis=0)
# california_housing_dataframe.drop(index=0, axis=0) 

# # remove HouseAge and population  column (axis=1)
# california_housing_dataframe.drop(columns=['HouseAge','Population'], axis=1)

## Data Cleansing

Remove rows containing missing values

In [84]:
# # create new DF by removing rows with empty cell
# df_cleansed=df_name.dropna()

# #Overwrite Original DF after removing rows with empty cell
# df_name.dropna(inplace = True)

Relpace missing values with mean ,median or mode

In [86]:
# # Replace by the specified value
# df_name.fillna(‘value_to_replace’, inplace = True)

# # Replace Using Mean, Median, or Mode
# mean_of_df=df_name[‘label’].mean()
# df_name[‘label’].fillna(mean_of_df , inplace = True)

Discover and remove duplicates

In [112]:
# # discover duplicates
# california_housing_dataframe.duplicated()

# #remove Duplicates
# california_housing_dataframe.drop_duplicates(inplace=True)

0        False
1        False
2        False
3        False
4        False
         ...  
20635    False
20636    False
20637    False
20638    False
20639    False
Length: 20640, dtype: bool